// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.


const ImageCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  object-fit: cover;
  height: 296px;
  background-color: rgba(39, 37, 37, 1);
`;

export default ImageCss;