name: 'Build components'

on:
  push:
    branches:
      - main

jobs:
  build-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install --force
          npm install react react-dom styled-components prop-types --save
      - name: Build components
        run: |
          npm run build