name: 'Release components'

on:
  push:
    tags:
      - "v*"

jobs:
  build-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install --force
          npm install react react-dom styled-components prop-types --save
      - name: Build components
        run: |
          npm run build
      - name: Release components
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_NAME }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}